### ISSUE TITLE
PHP 5.6

### ISSUE THREAD

**Issue by Medesis** [jokumer/eepcollect#1]
Hello,
we use this extension in our project.
But we have problems with the PHP version.
Every time we want to install extensions via composer, we must switch the PHP version.
We use PHP 5.6.3.

It is possible to change the dependencies form PHP to 5.6.99?

Best regards,
Jan

**Comment by jokumer** [comment]
I will do so.

**Comment by jokumer** [comment]
Done with release 1.0.19 with compatibility for TYPO3 CMS 7.6x - 8.7.x
